package com.limegroup.gnutella.gui.player;

import java.util.EventListener;

/**
 * Listener for events generated by the AudioPlayer
 */
public interface AudioPlayerListener extends EventListener {

	/**
     * Open callback, stream is ready to play.
     * 
     * properties map includes audio format dependant features such as bitrate,
     * duration, frequency, channels, number of frames, vbr flag, id3v2/id3v1
     * (for MP3 only), comments (for Ogg Vorbis), ...
     * 
     * @param properties audio stream properties.
	 */
    public void songOpened(AudioMetaData metaData);
	
    public void progressChange(float currentTimeInSecs);
	
    /**
     * Notification callback for basicplayer events such as opened, eom ...
	 *
     * @param event
	 */
    public void stateChange(AudioPlayerEvent event);
}

