#!/bin/bash

### Run script for FrostWire.
### Builds a classpath for all jars & components.
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
CLASSPATH=
PS=":"

OPTS="-Xms64m -Xmx256m -Djava.net.preferIPV6Addresses=false -ea -Djava.net.preferIPv4stack=true"

#setup the java options & initial system-dependent classpath
PLATFORM=`uname`
case ${PLATFORM} in 
    Linux)
        OPTS="${OPTS} -Djava.library.path=../lib/native";
        OPTS="${OPTS} -XX:-UseSplitVerifier ";
        export PATH="${PATH}:../lib/native";
        ADDITIONAL=linux
    ;;
    Darwin)
        CLASSPATH="${CLASSPATH}:/System/Library/Java";
        OPTS="${OPTS} -Djava.library.path=../lib/native";
        OPTS="${OPTS} -Djava.endorsed.dirs=\"\"";
        OPTS="${OPTS} -Djava.nio.preferSelect=true";
        OPTS="${OPTS} -Xdock:icon=FrostWire.icns";
        OPTS="${OPTS} -Dcom.sun.management.jmxremote.port=9595";
        OPTS="${OPTS} -Dcom.sun.management.jmxremote.ssl=false";
        OPTS="${OPTS} -Dcom.sun.management.jmxremote.authenticate=false";
	OPTS="${OPTS} -Djava.rmi.server.hostname=127.0.0.1";
        OPTS="${OPTS} -Dawt.useSystemAAFontSettings=on";
        OPTS="${OPTS} -Dswing.aatext=true";
        OPTS="${OPTS} -Dsun.java2d.opengl=True";
        ADDITIONAL=osx
    ;;
    CYGWIN*)
        PS=";"
        export PATH=$PATH:../lib/native
        ADDITIONAL=windows
        
    ;;
    *)
        echo "Sorry, platform '${platform}' is not recognized.";
        exit 1;
    ;;
esac

CLASSPATH="${CLASSPATH}${PS}.${PS}../core"

#add all the jars.
for JAR in $(find ../lib/jars -maxdepth 1 -name "*.jar"); do 
   CLASSPATH="${CLASSPATH}${PS}${JAR}"
done

#add all the additional jars.
for JAR in $(find ../lib/jars/${ADDITIONAL} -maxdepth 1 -name "*.jar" ); do 
   CLASSPATH="${CLASSPATH}${PS}${JAR}"
done

#add all the other jars.
for JAR in $(find ../lib/jars/other -maxdepth 1 -name "*.jar" ); do 
   CLASSPATH="${CLASSPATH}${PS}${JAR}"
done

#add all the components.
for COMPONENT in $(ls ../components); do
	if [ -d "../components/${COMPONENT}/src" ]
	then
		CLASSPATH="${CLASSPATH}${PS}../components/${COMPONENT}/build/classes${PS}../components/${COMPONENT}/src/main/resources"
	fi
done

export CLASSPATH
echo $CLASSPATH

export JAVA_BIN=${JAVA_HOME}/bin/java

echo Java Home:
echo ${JAVA_HOME}
echo Java Binary:
echo ${JAVA_BIN}
echo Java Version:
$JAVA_BIN -version
echo
echo "Let's go!"

case ${PLATFORM} in
    Darwin)
        ${JAVA_BIN} ${OPTS} -Xdock:name="FrostWire GIT" -Ddebug=1 com.limegroup.gnutella.gui.Main $* ;;
    *)
        ${JAVA_BIN} ${OPTS} -Ddebug=1 com.limegroup.gnutella.gui.Main $* ;;
esac
