package com.frostwire.gui.player;

import com.frostwire.mplayer.MediaPlaybackState;

/**
 * Listener for events generated by the AudioPlayer
 */
public interface MediaPlayerListener {

    /**
     * Open callback, stream is ready to play.
     */
    public void mediaOpened(MediaPlayer audioPlayer, AudioSource audioSource);

    public void progressChange(MediaPlayer audioPlayer, float currentTimeInSecs);
    
    public void volumeChange(MediaPlayer audioPlayer, double currentVolume);

    /**
     * Notification callback for basicplayer events such as opened, eom ...
     *
     * @param event
     */
    public void stateChange(MediaPlayer audioPlayer, MediaPlaybackState state);
    
    public void icyInfo(MediaPlayer audioPlayer, String data);
}
